docker:
  host: "${DOCKER_IP:localhost}"

spring:
  datasource:
    url: "jdbc:postgresql://${docker.host}:5432/postgres?currentSchema=basketcoach"
    username: postgres
    password: basketcoach
  flyway:
    locations: classpath:db/migration, classpath:db/init
